### ISSUE TITLE
publish release notes

### ISSUE THREAD

**Issue by codyoss** [actions/github-script#140]
**Is your feature request related to a problem? Please describe.**

Right now I receive automated updates from renovate to bump dependencies. I recently got one to go from v3 to v4 of github-script. Without release notes it is hard for me, non-javascript expert, to understand why there was a major version bump. Was there a security issue, breaking changes that I need to know about, dependencies, etc.?

**Describe the solution you'd like**

It would be nice if, at least for major version release, a GitHub release was drafted with relevant information.

**Describe alternatives you've considered**

Provide a changelog or something similar.

**Comment by jclem** [comment]
The releases and release notes are available on the "Releases" page for this repository: https://github.com/actions/github-script/releases

**Comment by codyoss** [comment]
@jclem Looking at the v4.0.0 release for example: https://github.com/actions/github-script/releases/tag/v4.0.0

> This release adds support for relative require paths, as well as requiring npm modules installed in the working directory.

This does not really tell me why this is a major version release and if there are any upgrade paths, deprecations, etc. Why is this a major version in this case?

**Comment by jclem** [comment]
@codyoss Yup, this could be more clear. However, in this case, there is no suggested upgrade path, and there are no deprecations. We expect this release to continue to work for every single user, but only created a major release because technically speaking, the identity of the `require` function is not the same as it was before.

Release notes aside, my advice generally is to always inspect a diff using a URL such as https://github.com/actions/github-script/compare/v3.1.1...v4.0.0 before upgrading any action.

**Comment by jclem** [comment]
> Although this action requires writing a bit of javascript that does not make me an expert of why the changes might be breaking.

That's a good point, thanks for the feedback! I'll take that into account more in future releases.

**Comment by alexcroox** [comment]
Agreed, I have come here from my renovate bot telling me I'm upgrading a major version to v4. I see no breaking changes listed in the releases page, I also see multiple v4 releases:

v4.0.0
v4
v4.0

I read them all but still aren't confident of updating a major version.
