### ISSUE TITLE
"cancelInvitation" not found

### ISSUE THREAD

**Issue by Timmmy-nlb** [actions/github-script#155]
**Describe the bug**
A method, which should be available according to the documentation of octokit, does not exist.
I get error `Unhandled error: TypeError: github.orgs.cancelInvitation is not a function`.
Other like `github.orgs.listPendingInvitations`  works as expected.

**To Reproduce**
```javascript
- name: CancelInvitation
  uses: actions/github-script@v4
  [...]
  script: |
       github.orgs.cancelInvitation({
                org: "organization",
                invitation_id: 00000,
        });
```

A call from `console.log('Test: ', github.orgs);` shows that the method is really missing.

**Expected behavior**
That the method can be used, as the other.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox, Chrome

**Additional context**
coming from this help ticket https://github.com/octokit/plugin-rest-endpoint-methods.js/issues/403

**Comment by Simran-B** [comment]
The endpoint was added upstream via https://github.com/octokit/plugin-rest-endpoint-methods.js/pull/320 in January ([v4.6.0](https://github.com/octokit/plugin-rest-endpoint-methods.js/releases/tag/v4.6.0)) 😞 
#133 is also caused by outdated dependencies. However, I tried to bump everything to latest but it's still missing the methods for some reason - am I doing something wrong?
- Workflow run: https://github.com/Simran-B/test-workflows/runs/2906360996#step:3:28
- Workflow: https://github.com/Simran-B/test-workflows/actions/runs/968505516/workflow
- Forked Action: https://github.com/Simran-B/github-script/commits/main

**Comment by Simran-B** [comment]
Found the problem: Octokit used to expose REST endpoints directly, like `octokit.actions.cancelWorkflowRun`. They are now nested under `octokit.rest`, e.g. `octokit.rest.actions.cancelWorkflowRun`. My updated `github-script` action works if I  use `github.rest.*` instead of `github.*`.

**Comment by Timmmy-nlb** [comment]
Is there anything I can do or test so that we can continue this issue?

**Comment by joshmgross** [comment]
👋  Hey @Timmmy-nlb,

I've just released https://github.com/actions/github-script/releases/tag/v5.0.0 which includes the latest version of Octokit with this API.

Note you'll need to update your script to use `github.rest.orgs.cancelInvitation ` due to changes in Octokit, see https://github.com/actions/github-script#breaking-changes-in-v5.

Feel free to reopen this issue if you're still seeing issues.
