### ISSUE TITLE
Github packages API

### ISSUE THREAD

**Issue by hjaved-nha** [actions/github-script#179]
Hi,

I'm using github-script in github actions to access packages api `github.packages.getPackageVersionForOrganization` but getting the following error

`Cannot read property 'getPackageVersionForOrganization' of undefined`

Is it possible to access the packages api via github-script or am I doing something wrong ?

Kind Regards.

**Comment by joshmgross** [comment]
👋  Hey @hjaved-nha,

I've just released https://github.com/actions/github-script/releases/tag/v5.0.0 which includes the latest version of Octokit with this API.

Note you'll need to update your script to use `github.rest.packages.getPackageVersionForOrganization` due to changes in Octokit, see https://github.com/actions/github-script#breaking-changes-in-v5.

Feel free to reopen this issue if you're still seeing issues.
