### ISSUE TITLE
Why does node version not follow the actions/setup-node?

### ISSUE THREAD

**Issue by hellodword** [actions/github-script#241]
v5 only use node v12, and the `setup-node` [does not work](https://github.com/hellodword/github-script-debug/actions/runs/1828844973).

I found the pr https://github.com/actions/github-script/pull/235 and tried it with `uses: actions/github-script@master`, now it always use node v16.

As this issue comment [said](https://github.com/actions/github-script/issues/76#issuecomment-669199990)

> Unless actions/setup-node is explicitly used, for our hosted runners, the version of Node.js will be whatever is installed in the virtual environment you're using (for example ubuntu-latest). This is documented in "Software installed on GitHub-hosted runners". For example, the current ubuntu-latest, which is 18.04, uses Node.js 12.18.3.

I think this is the best way. 

Or is there any security considering that I don't know?

**Comment by joshmgross** [comment]
👋  Hey @hellodword,

I don't think that comment is correct - due to how this action is wrapping the passed in script, the version of node used will match the version used by the action 

https://github.com/actions/github-script/blob/main/src/async-function.ts

https://github.com/actions/github-script/blob/9ac08808f993958e9de277fe43a64532a609130e/action.yml#L30

The Actions runner bundles its own version of Node to run JavaScript actions - so the version of Node installed by `setup-node` will never be used.

**Comment by hellodword** [comment]
Thanks @joshmgross,

so it's kind of a [limit](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions) of github actions, right?

Seems it only has `node12` and `node16`, and we can't use dynamic node version as runtime.

**Comment by joshmgross** [comment]
>so it's kind of a [limit](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions) of github actions, right?

That's correct
