### ISSUE TITLE
Update to Node 18 since it is now LTS.

### ISSUE THREAD

**Issue by JamesKyburz** [actions/github-script#310]
Please update the node version to 18 as it is now LTS.

**Comment by joshmgross** [comment]
Only Node 12 and 16 are supported by the Actions runner - 

https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-javascript-actions

Node 12 is currently being deprecated - https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/


If you'd like to use actions with Node 18, I'd recommend filing an issue in the runner repository or adding a comment to an existing issue (ex: https://github.com/actions/runner/issues/2255).

If you just need to run a script with Node 18, I'd recommend using [`actions/setup-node`](https://github.com/actions/setup-node) to install Node 18 and running your script with `node` directly rather than using this action.
