### ISSUE TITLE
How to make conditional check on a label name that includes emoji

### ISSUE THREAD

**Issue by guardrex** [actions/github-script#441]
On the Microsoft ASP.NET Core documentation repo, we use a label with a watch emoji (`:watch:`, ⌚) in our not-triaged label.

The label is ...

⌚ Not Triaged

When we try to make a conditional check for the watch emoji in a workflow that removes this label under some conditions based on the presence of other labels, either the emoji in the check fails to match or throws a syntax error.

Here are the two cases that we've tried ...

### Using colon syntax

```yml
if: github.event.label.name == ':watch: Not Triaged' && (github.event.label.name == 'aspnetcore-blazorhybrid/tech' || github.event.label.name == 'aspnetcore-blazor/tech')
```

Result: The line throws a syntax error in the GH code editor ...

> incomplete explicit mapping pair; a key node is missed; or followed by a non-tabulated empty line

The workflow error when this is executed is ...

>  Invalid workflow file
>
> You have an error in your yaml syntax on line 104

I tried escaping the colons with backslashes, and I also tried using the `${{ ... }}` syntax around the conditional expression. Neither approach works.

### Using the graphic emoji

```yml
if: github.event.label.name == '⌚ Not Triaged' && (github.event.label.name == 'aspnetcore-blazorhybrid/tech' || github.event.label.name == 'aspnetcore-blazor/tech')
```

Result: Doesn't throw a syntax error, nor does it cause the workflow to log an error when it runs. ***However***, it fails to match on the label name, so the workflow job fails to execute our script.

### How can we address this?

Is there an approach to deal with this? Is this a bug in your processing that you'd like to fix? If it is a bug that will be fixed, is there a workaround approach that I can use in the meantime?

If this isn't a bug, documentation for `if:` syntax probably should explain how to address it at ...

https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution

Cross-reference to our entire workflow script: https://github.com/dotnet/AspNetCore.Docs/blob/main/.github/workflows/issue-processing.yml

☝️ See ***Line 104*** of the workflow, which doesn't throw a syntax error but doesn't work.

**Comment by joshmgross** [comment]
👋 @guardrex 

From some quick personal testing, the full Unicode emoji is correct here.
https://github.com/joshmgross/actions-testing/commit/0e102cf9d1351ca2b065f759589fe05e60533de6

You can see in this run that the label includes the unicode emoji insteaad of emoji name within `:`.

I believe the issue lies in your expressionn itself, not the actual matching to a label:
```yaml
if: github.event.label.name == '⌚ Not Triaged' && (github.event.label.name == 'aspnetcore-blazorhybrid/tech' || github.event.label.name == 'aspnetcore-blazor/tech')
```

Your expression is matching against a single label so there's never a case where this will return true.
i.e. `github.event.label.name` *can't* equal one label and a separate label at the same time.

Looking at our [docs for that event payload](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=labeled#issues) - I suspect you want to compare against the full set of labels on the issue at the time of it being labeled.

Something like this might work:
```yaml
if: contains(github.event.issue.labels.*.name, '⌚ Not Triaged') && (contains(github.event.issue.labels.*.name, 'aspnetcore-blazorhybrid/tech') || contains(github.event.issue.labels.*.name, 'aspnetcore-blazor/tech'))
```

If you specifically only want this to run when `'⌚ Not Triaged'` rather than when another of those labels is added, then you'd want to keep the `github.event.label.name == '⌚ Not Triaged'` at the beginning of the `if`.

If that doesn't work or you want to adjust it further, I'd recommend enabling debug logging to help identify how the expressions are being evaluted - https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging#enabling-step-debug-logging.

**Comment by guardrex** [comment]
Ah ha! Thanks for clearing this up, @joshmgross. I'll send in a feedback note on the `if:` doc to mention that I didn't understand how labels can be checked.
