### ISSUE TITLE
Add helper function for reading YAML

### ISSUE THREAD

**Issue by jasonmacgowan** [actions/github-script#53]
A common pattern I've seen (and used) for complex configuration of an action is to read a file in the `.github` directory of a repo.  Usually these files are `yaml`.

How about adding a yaml loader helper script to the global context (attach to `github` or `context` maybe?)

I'm happy to implement it, but wanted to start a discussion first.

**Comment by jclem** [comment]
@jasonmacgowan I haven't seen this pattern, personally, can you point me to some examples?

**Comment by jasonmacgowan** [comment]
@jclem sorry about this delay, I thought I responded!

I mispoke when I said this was common pattern for actions.  I meant we see this pattern implement for [probot](https://github.com/probot/probot) and I think it works really well.

Examples:
- [probot/settings](https://github.com/probot/settings)
- [probot/stale](https://github.com/probot/stale)

**Comment by jclem** [comment]
I see what you mean now @jasonmacgowan, thanks. I don't plan on adding YAML parsing directly to this action to solve those use cases—the goals are a bit different between this action and the Probot repositories you linked to. This action is meant to be consumed by a workflow author in order to quickly automate some basic GitHub tasks, but that use of this action by that author wouldn't really be _distributed_ to other Actions users via the marketplace, if that makes sense.

You could certainly reproduce them in a one-off fashion by providing config in the workflow file itself and then using the GitHub client provided by this action to apply repo settings, for example. However, if you wanted something reusable across repositories, a better solution would be to just build a publicly-usable action, like [actions/stale](https://github.com/actions/stale) using the [Actions toolkit](https://github.com/actions/toolkit). For example, I can see an action for repo settings working something like this from the consumer end:

```yaml
uses: jasonmacgowan/repo-settings@v1
with:
  has_issues: true
  has_wiki: false
```

Under the hood, that action would just use the toolkit to read the user-provided inputs and make API calls.
