### ISSUE TITLE
what is the equivalent of issue_number: context.issue.number for pull-request ?

### ISSUE THREAD

**Issue by ojedavidea** [actions/github-script#64]
Thank you 🙇‍♀ for wanting to create an issue in this repository. Before you do, please ensure you are filing the issue in the right place. Issues should only be opened on if the issue **relates to code in this repository**.

* If you have found a security issue [please submit it here](https://hackerone.com/github)
* If you have questions about writing workflows or action files, then please [visit the GitHub Community Forum's Actions Board](https://github.community/t5/GitHub-Actions/bd-p/actions)
* If you are having an issue or question about GitHub Actions then please [contact customer support](https://help.github.com/en/articles/about-github-actions#contacting-support)

If your issue is relevant to this repository, please delete this text and continue to create this issue. Thank you in advance.

**Comment by jclem** [comment]
@ojedavidea This repository is just for the "github-script" action. I recommend looking at the [GitHub Actions documentation](https://docs.github.com/en/actions), specifically ["Events that trigger workflows"](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request). It's also worth reading the [@actions/github documentation](https://github.com/actions/toolkit/tree/master/packages/github).

The PR number is in the same place as an issue number—`context.issue.number`.

**Comment by ojedavidea** [comment]
just puke the code please...

is it `context.issue.number` or `context.pullrequest.number` or `context.pull-request.number` or `context.pr.number` or `context.p-r.number` or `context.pull_request.number` or `context.p_r.number` or `context.pullRequest.number` or anything else weirder than that....?

I just want the code for automatically comment something after a pull-request using the github actions, p.l.e.a.s.e.

**Comment by jclem** [comment]
> just puke the code please...

I'm not sure if this wording was intentional (or maybe a typo), but just wanted to let you know that this comes off as a little bit  aggressive. I certainly don't feel like vomiting today 😄 I'm assuming this was an accident, though!

To answer your question a little more clearly, the PR number is at `context.issue.number`—the same place an issue number would be. There's a lot of similarity between issues and PRs conceptually, so you'll frequently see some overlap like this in the GitHub ecosystem.

For an example of commenting on a pull request, this very repository actually has such a workflow 😄, which you can see [here](https://github.com/actions/github-script/blob/b507739f17c2106b2a1a596000eaa49a0d5c33a2/.github/workflows/pull-request-test.yml#L13-L39) for an example. Note that I'm using `context.payload.number` to get the PR number. It's in both places.

This repository is just _one_ way of getting things done with GitHub Actions, though. For general questions like "How do I comment on a PR after it's opened?" the [GitHub Support Community](https://github.community/c/github-actions/41) is by far the best place to go! There are tons of friendly people there happy to help you find answers (and probably more quickly than I can respond in this one repository).

**Comment by francisfuzz** [comment]
> For an example of commenting on a pull request, this very repository actually has such a workflow 😄, which you can see here for an example. Note that I'm using context.payload.number to get the PR number. It's in both places.

👋  Hello, @ojedavidea! I'd like to share another end-to-end example for commenting on a pull request, in the case that it helps:

* Repository: https://github.com/actions-packages-examples/comment-on-a-pull-request
* Workflow file: https://github.com/actions-packages-examples/comment-on-a-pull-request/blob/master/.github/workflows/comment-on-a-pull-request.yml
* Workflow run: https://github.com/actions-packages-examples/comment-on-a-pull-request/runs/855001143?check_suite_focus=true

This particular workflow file copies the [comment on an issue example documented in the README](https://github.com/actions/github-script#comment-on-an-issue), replacing `issue` with `pull_request`. 

As @jclem had previously mentioned, the [`@actions/github` documentation](https://github.com/actions/toolkit/tree/master/packages/github) is a pretty great way to get a better understanding of how `context` is used. Granted, after reviewing that guide and  the contents of [`src/context.ts`](https://github.com/actions/toolkit/blob/master/packages/github/src/context.ts) file, there may be an opportunity to document this further in that repository. If that's something you would like to see, you're welcome to [open an issue in that repository](https://github.com/actions/toolkit/issues) and someone might be able to help with that there since that's where `context` is defined.

> This repository is just one way of getting things done with GitHub Actions, though. For general questions like "How do I comment on a PR after it's opened?" the GitHub Support Community is by far the best place to go! There are tons of friendly people there happy to help you find answers (and probably more quickly than I can respond in this one repository).

💯  to this!

**Comment by richardpickett** [comment]
> To answer your question a little more clearly, the PR number is at context.issue.number—the same place an issue number would be.

This no longer seems to be the case, or isn't always the case.

I have PRs that trigger action workflows where `github.context.payload.issue.number` is undefined.

Sample code:

`import github from "@actions/github";

console.log(github.context.payload.issue.number);`

This will result in a "number not defined" error.
